#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     Inf,            sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     HTGYRO,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     yellow,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     red,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     blue,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     green,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
float wheels(float
float heading = 0;
#include "drivers/hitechnic-gyro.h"
void driveFor(int t){
		nMotorEncoder[yellow] = 0;
		nMotorEncoder[blue] = 0;
		while(nMotorEncoder[yellow] < t){
		  long X = (0*Cos((heading*PI)/180)) + (100*sin((heading*pi)/180));
		  long Y = (100*Cos((heading*PI)/180)) - (0*sin((heading*pi)/180));

		  motor[blue] = X+Y;
		  motor[yellow] = X-Y;
		  motor[green] = X+Y;
		  motor[red] = X-Y;
		}

	  motor[blue] = 0;
	  motor[green] = 0;
	  motor[yellow] = 0;
	  motor[red] = 0;
}
void driveToInf(){
	while(SensorValue[INF] != 5){
	  long X = (0*Cos((heading*PI)/180)) + (100*sin((heading*pi)/180));
	  long Y = (100*Cos((heading*PI)/180)) - (0*sin((heading*pi)/180));

	  motor(blue) = X+Y;
	  motor(green) = Y-X;
	  motor(yellow) = X-Y;
	  motor(red) = -X-Y;
	}

	motor(blue) = 0;
	motor(green) = 0;
	motor(yellow) = 0;
	motor(red) = 0;
}
void turnRight(int D){
	int

task main ()
{
 /*-----------------------------------Start Gyro Position Compensation-------------------------------*/
  float rotSpeed = 0;

  HTGYROstartCal(HTGYRO);

  time1[T1] = 0;

  while (true)
  {
    while (time1[T1] < 20)
      wait1Msec(1);

    time1[T1]=0;
    rotSpeed = HTGYROreadRot(HTGYRO);
    heading += rotSpeed * 0.02;

    nxtDisplayCenteredTextLine(3, "Gyro: %2.3f", heading);
  }
}
