#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     Inf,            sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     HTGYRO,         sensorAnalogInactive)
#pragma config(Motor,  mtr_S1_C1_1,     yellow,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     red,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     blue,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     green,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorK,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    test,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float heading = 0;
#include "drivers/hitechnic-gyro.h"

void driveToInf(){
	nMotorEncoder[yellow] = 0;
	while(SensorValue[Inf] != 5){
		motor(red) = -60;
		motor(yellow) = 60;
		motor(green) = -60;
		motor(blue) = 60;
	}
	motor(blue) = 0;
	motor(green) = 0;
	motor(yellow) = 0;
	motor(red) = 0;
	servo[test] = 65;
	wait1Msec(300000);
}
void turnRight(int right){
	nMotorEncoder[yellow] = 0;
	while((nMotorEncoder[yellow] * 360) > right *7000){
		motor(blue) = -50;
		motor(green) = -50;
		motor(yellow) = -50;
		motor(red) = -50;
	}

	motor(blue) = 0;
	motor(green) = 0;
	motor(yellow) = 0;
	motor(red) = 0;

}
void turnLeft(int left){
	nMotorEncoder[yellow] = 0;
	while((nMotorEncoder[yellow] * 360) < -left * 7000){
		motor(blue) = 50;
		motor(green) = 50;
		motor(yellow) = 50;
		motor(red) = 50;
	}

	motor(blue) = 0;
	motor(green) = 0;
	motor(yellow) = 0;
	motor(red) = 0;

}
void returnto(){
	time1[T1] = 0;
	while(nMotorEncoder[yellow] > 0 && time1[T1] < 7000){
		motor(red) = 60;
		motor(yellow) = -60;
		motor(green) = 60;
		motor(blue) = -60;
	}
}

task main ()
{
	driveToInf();
	returnto();

}