#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S2,     INF,            sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     RGB,            sensorCOLORFULL)
#pragma config(Motor,  mtr_S1_C1_1,     yellow,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     red,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     blue,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     green,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     whisk,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     lift,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     flag,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    autoflipper,          tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// teleopblockparty001.c

#include "JoystickDriver.c";
string direction = "yellow";
void initializeRobot(){
	nNoMessageCounterLimit = 100;
	servo[autoflipper] = 20;
	motor[arm] = 0;
	return;
}
float DZ(float input){
	if(input > -10 && input < 10){
		return 0;
		}else{
		return input;
	}
}
task directionCont(){
	while(true){
		getJoystickSettings(joystick);
		if(joy1Btn(1)){
			direction = "blue";
		}else if(joy1Btn(2)){
			direction = "yellow";
		}else if(joy1Btn(3)){
			direction = "red";
		}else if(joy1Btn(4)){
			direction = "green";
		}else if(joy2Btn(1)){
			direction = "blue";
		}else if(joy2Btn(2)){
			direction = "yellow";
		}else if(joy2Btn(3)){
			direction = "red";
		}else if(joy2Btn(4)){
			direction = "green";
		}
		abortTimeslice();
	}
}
task drive(){
	int turn;
	while(true){
		if(joystick.joy1_TopHat == 2){
			turn = 100;
		}else if(joystick.joy1_TopHat == 6){
			turn = -100;
		}else{
			turn = 0;
		}

		getJoystickSettings(joystick);
		if(direction == "red"){
			motor[yellow] = (((DZ(joystick.joy1_y1)+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[blue] = (((DZ(joystick.joy1_y1)-DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[green] = -(((DZ(joystick.joy1_y1)+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[red] = (((DZ(joystick.joy1_x1)-DZ(joystick.joy1_y1))/128.0)*100) - turn;

		}else if(direction == "yellow"){
			//default direction
			motor[red] = (((DZ(joystick.joy1_y1)+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[yellow] = (((DZ(joystick.joy1_y1)-DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[blue] = -(((DZ(joystick.joy1_y1)+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[green] = (((DZ(joystick.joy1_x1)-DZ(joystick.joy1_y1))/128.0)*100) - turn;

		}else if(direction == "blue"){
			motor[green] = (((DZ(joystick.joy1_y1)+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[red] = (((DZ(joystick.joy1_y1)-DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[yellow] = -(((DZ(joystick.joy1_y1)+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[blue] = (((DZ(joystick.joy1_x1)-DZ(joystick.joy1_y1))/128.0)*100) - turn;

		}else if(direction == "green"){
			motor[blue] = (((DZ(joystick.joy1_y1)+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[green] = (((DZ(joystick.joy1_y1)-DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[red] = -(((DZ(joystick.joy1_y1)+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[yellow] = (((DZ(joystick.joy1_x1)-DZ(joystick.joy1_y1))/128.0)*100) - turn;
		}
	}
}
task lifter(){
	while(true){
		if(joy1Btn(8)){
			motor[lift] = -100;
		}else if(joy1Btn(6)){
			motor[lift] = 100;
		}else if(joy2Btn(8)){
			motor[lift] = -100;
		}else if(joy2Btn(6)){
			motor[lift] = 100;
		}else{
			motor[lift] = 0;
		}
		abortTimeslice();
	}
}
task flagger(){
	while(true){
		if(joy1Btn(5)){
			motor[flag] = 100;
		}else if(joy2Btn(5)){
			motor[flag] = 100;
		}else{
			motor[flag] = 0;
		}
		abortTimeslice();
	}
}
task armer(){
	while(true){
		if(joystick.joy1_TopHat == 4){
			motor[arm] = -60;
		}else if(joystick.joy1_TopHat == 0){
			motor[arm] = 60;
		}else if(joystick.joy2_TopHat == 0){
			motor[arm] = 60;
		}else if(joystick.joy2_TopHat == 4){
			motor[arm] = -60;
		}else{
			motor[arm] = 0;
		}

		if(DZ(joystick.joy1_y2) > 15){
			servo[wrist] -= ((DZ(joystick.joy1_y2))/100);
		}else if(DZ(joystick.joy1_y2) < -15){
			servo[wrist] -= ((DZ(joystick.joy1_y2))/100);
		}else if(DZ(joystick.joy2_y2) > 15){
			servo[wrist] -= ((DZ(joystick.joy2_y2))/100);
		}else if(DZ(joystick.joy2_y2) < -15){
			servo[wrist] -= ((DZ(joystick.joy2_y2))/100);
		}else if(joy1Btn(9)){
			servo[wrist] = 0;
		}else if(joy1Btn(10)){
			servo[wrist] = 193;
		}else if(joy2Btn(10)){
			servo[wrist] = 0;
		}else if(joy2Btn(9)){
			servo[wrist] = 193;
		}
		abortTimeslice();
	}
}
task whisker(){
	while(true){
		if(joy1Btn(7)){
			motor[whisk] = 100;
		}else if(joy2Btn(7)){
			motor[whisk] = 100;
		}else{
			motor[whisk] = 0;
		}
		abortTimeslice();
	}
}
task main(){
	initializeRobot();

	waitForStart();

	StartTask(directionCont);

	StartTask(drive);

	StartTask(lifter);

	StartTask(armer);

	StartTask(flagger);

	StartTask(whisker);
	while(true){
		nxtDisplayTextLine(1,"%f",servo[wrist]);
	}
}
//0 is up, 193 is vertical