#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     controller,     sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     DR,            tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     DL,            tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Scissors,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Has 2013 States Pragma
#include "JoystickDriver.c"



void initializeRobot()
{
	//250 counts = 1 sec
	nNoMessageCounterLimit = 325;

	servoChangeRate[claw] = 2;

  servo[claw] = 240;

  return;
}
/*------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------*/
float DZ(float input){
	float output;
	if(abs(input)<10){
		output = 0;
	}
	else{
		output = input;
	}
	return output;
}
/*------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------*/
float fineMotorControl(float input){
	float output;
	float Derp = pow(input, 3.0);
	output = Derp/20750.0;
	return output;
}
/*------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------*/
task scissor(){
	while (true)
	{
		getJoystickSettings(joystick);
		if(joystick.joy1_TopHat == 0){
			motor[Scissors] = 100;
		}
		else if(joystick.joy1_TopHat == 4){
			motor[Scissors] = -50;
		}
		else if(joy1Btn(5)){
			motor[Scissors] = 50;
		}
		else if(joy1Btn(7)){
			motor[Scissors] = -30;
		}
		else if(joystick.joy2_TopHat == 0){
			motor[Scissors] = 100;
		}
		else if(joystick.joy2_TopHat == 4){
			motor[Scissors] = -50;
		}
		else if(joy2Btn(5)){
			motor[Scissors] = 50;
		}
		else if(joy2Btn(7)){
			motor[Scissors] = -30;
		}else{
			motor[Scissors] = 0;
		}
		wait10Msec(1);
	}
}
/*------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------*/
task drive(){

		float speed;
		speed = 1;
		int switcha = 0;
		int switchb = 1;

	while (true)
  {

  	getJoystickSettings(joystick);
  	if(joy1Btn(1) && (switcha == 0)){
  		switcha = 1;
  		PlayImmediateTone(1000,50);
  	}
  	if((joy1Btn(1) == 0) && (switcha == 1)){
  		switcha = 0;
  		switchb *= -1;
  		PlayImmediateTone(2000,50);
  	}


  	if(switchb == 1){

  	if(abs(joystick.joy1_y1 - joystick.joy1_y2) > 50){
  		speed = .5;
  	}else{
  		speed = 1;
  	}

		 	if(abs((DZ(fineMotorControl(joystick.joy1_y1)))) > 10){
				motor[DL] = (int)(speed * (DZ(fineMotorControl(joystick.joy1_y1))));
			}
			else{
				motor[DL] = (int)(speed * DZ(fineMotorControl(joystick.joy2_y1)));
			}

			if(abs((DZ(fineMotorControl(joystick.joy1_y2)))) > 10){
				motor[DR] = (int)(speed * (DZ(fineMotorControl(joystick.joy1_y2))));
			}
			else{
				motor[DR] = (int)(speed * (DZ(fineMotorControl(joystick.joy2_y2))));
			}
			wait10Msec(1);
		}
		if(switchb == -1){
			if(abs((DZ(fineMotorControl(joystick.joy1_y1)))) > 10){
				motor[DL] = (int)((.2) * speed * (DZ(fineMotorControl(joystick.joy1_y1))));
			}
			else{
				motor[DL] = (int)((.2) * speed * DZ(fineMotorControl(joystick.joy2_y1)));
			}

			if(abs((DZ(fineMotorControl(joystick.joy1_y2)))) > 10){
				motor[DR] = (int)((.2) * speed * (DZ(fineMotorControl(joystick.joy1_y2))));
			}
			else{
				motor[DR] = (int)((.2) * speed * (DZ(fineMotorControl(joystick.joy2_y2))));
			}
			wait10Msec(1);
	  }
	}
}

/*------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------*/
task clawz(){
	while(true){
		if(joy1Btn(6)){
		servo[claw] += 1;
		}
		else if(joy1Btn(8)){
		servo[claw] -= 1;
		}
		else if(joy2Btn(6)){
		servo[claw] += 1;
		}
		else if(joy2Btn(8)){
		servo[claw] -= 1;
		}else if(joy1Btn(4)){
		servo[claw] = 92;
		}
		else if(joy2Btn(4)){
			servo[claw] = 92;
		}
		else if(joy1Btn(3)){
			servo[claw] = 119;
		}
		else if(joy2Btn(3)){
			servo[claw] = 119;
		}
		wait10Msec(1);
	}
}
/*------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------*/
task super(){
	while(true){
	getJoystickSettings(joystick);
		if(joy1Btn(5)){
			servo[claw] -= 1;
		}
		if(joy2Btn(5)){
			servo[claw] -= 1;
		}
		wait10Msec(6);
	}
}
/*------------------------------------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------------------------------------*/
task main(){
  initializeRobot();

  waitForStart();

  StartTask(drive);

  StartTask(scissor);

  StartTask(clawz);

  StartTask(super);

  while(true){
  }

}
