#pragma config(Hubs,  S3, HTServo,  none,     none,     none)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S3_C1_1,    flipper,              tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//toggle dat servo.c

task main()
{
	int switcha = 0;
	int switchb = 1;
	servo[flipper] = 0;

	while(true){

		if((nNxtButtonPressed == 1) && (switcha == 0)){
			switcha = 1;
		}
		if((nNxtButtonPressed != 1) && (switcha == 1)){
			switcha = 0;
			switchb *= -1;
		}
		if(switchb == 1){
			servo[flipper] = 0;
			}else{
			servo[flipper] = 255;
		}

		//Switchb will represent which toggle you are in
	}
}
